version: "3.8"
services:
  frontend:
    build:
      # for manual build process
      # context: ./conduit-frontend
      # dockerfile: Dockerfile
      # for build with GitHub Actions
      image: ghcr.io/sarahzimmermann-schmutzler/conduit-frontend:latest
      args:
        # passes the value from .env to Dockerfile for building process
        - API_URL=${API_URL}
    env_file: .env
    container_name: conduit-frontend
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:80
    restart: on-failure
    networks:
      - conduit-network

  backend:
    build:
      # for manual build process
      # context: ./conduit-backend
      # dockerfile: Dockerfile
      # for build with GitHub Action
      image: ghcr.io/sarahzimmermann-schmutzler/conduit-backend:latest
    env_file: .env
    container_name: conduit-backend
    volumes:
      # mount for the database directory
      - conduit-volume:/app/db
    ports:
      - ${BACKEND_EXTERNAL_PORT}:8000
    restart: on-failure
    networks:
      - conduit-network

volumes:
  conduit-volume:

networks:
  conduit-network: