version: "3.8"
services:
  frontend:
    build:
      context: ./conduit-frontend
      dockerfile: Dockerfile
      args:
        # passes the value from .env to Dockerfile for building process
        - API_URL=${API_URL}
    env_file: .env
    container_name: conduit-frontend
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:${FRONTEND_INTERNAL_PORT}"
    restart: on-failure
    networks:
      - conduit-network

  backend:
    build:
      context: ./conduit-backend
      dockerfile: Dockerfile
    env_file: .env
    container_name: conduit-backend
    volumes:
      # mount for the database directory
      - conduit-volume:/app/db
    ports:
      - "${BACKEND_EXTERNAL_PORT}:${BACKEND_INTERNAL_PORT}"
    restart: on-failure
    networks:
      - conduit-network

volumes:
  conduit-volume:

networks:
  conduit-network: