version: "3.8"
services:
  frontend:
    build:
      context: ./conduit-frontend
      args:
        # passes the value from .env to Dockerfile for building process
        - API_URL=${API_URL}
    env_file: .env
    container_name: conduit-frontend
    ports:
      - 8282:80
    restart: on-failure
    networks:
      - conduit-network

  backend:
    build:
      context: ./conduit-backend
    env_file: .env
    container_name: conduit-backend
    volumes:
      # mount for the database directory
      - conduit-volume:/app/db
    ports:
      - 8383:8000
    restart: on-failure
    networks:
      - conduit-network

volumes:
  conduit-volume:

networks:
  conduit-network: